In [1]:
from fastai.vision.all import *

In [4]:
path = untar_data(URLs.PETS)/'images'

Downloading a new version of this dataset...

In [6]:
def is_cat(x):
    return x[0].isupper()

In [7]:
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat, item_tfms=Resize(224))

In [9]:
learn = vision_learner(dls, resnet34, metrics=error_rate)

In [11]:
learn.fine_tune(2)